from tkinter import *

root = Tk()
root.geometry('300x300')
root.title('Madlibs Generator')
Label(root, text= 'Mad libs Generator', font='arial 20 bold').pack()
Label(root, text= 'Click Any One', font='arial 15 bold').place(x=40, y=80)

def madlib1():
    
    verb1 = input('Enter a verb (past tense): ')
    noun1 = input('Enter a noun: ')
    verb2 = input('Enter a verb (past tense): ')
    verb3 = input('Enter a verb: ')
    noun2 = input('Enter a noun: ')
    noun3 = input('Enter a noun: ')
    adjective1 = input('Enter an adjective: ')
    verb4 = input('Enter a verb (past tense): ')
    noun4 = input('Enter a noun: ')
    adjective2 = input('Enter an adjective: ')
    place1 = input('Enter a place: ')
    verb5 = input('Enter a verb (past tense): ')
    adjective3 = input('Enter an adjective: ')
    yourName = input('Enter your name: ')
    partnerName = input('Enter the name of your partner: ')
    noun5 = input('Enter a noun: ')
    verb6 = input('Enter a verb: ') 
    adjective4 = input('Enter an adjective: ')
    adjective5 = input ('Enter an adjective: ')
    verb7 = input('Enter a verb: ') 
    verb8 = input('Enter a verb: ')
    noun6 = input('Enter a noun: ')
    print('Before we ' + verb1 + ', ' + 'I did not believe in love at first ' + noun1 + ', but you completely ' + verb2 + ' my breath away. From the first time we '  + verb3 + ', I knew you were the  ' + noun2 + '. Although our first ' + noun3 + ' was a little ' + adjective1 + ', especially after you ' + verb4 + 'into the ' + noun4 + ' at that ' + adjective2 + ' ' + place1 + ', you just ' + verb5 + ' back up and laughed. That is when I knew you were someone ' + adjective3 + '. I, ' + yourName + ', take you ' + partnerName + ' to be my beloved husband/wife. When you need a ' + noun5 + ', I will be a ' + noun5 + ' to you. When you need ' + verb6 + ' along the way, I will ' + verb6 + ' you. I will always be there for you, for better or for ' + adjective4 + ', for richer or for ' + adjective5 + ', in sickness and in health, to have and to ' + verb7 + ' for the rest of my life. I promise to love you and ' + verb8 + ' you forever. Till ' + noun6 + 'do us part.')

def madlib2():
    
    partnerName2 = input('Enter the name of your partner: ')
    verb1 = input('Enter a verb: ')
    noun1 = input('Enter a noun: ')
    noun2 = input('Enter a noun: ')
    noun3 = input('Enter a noun: ')
    verb2 = input('Enter a verb: ')
    noun4 = input('Enter an noun: ')
    adjective1 = input('Enter an adjective: ')
    adjective2 = input('Enter an adjective: ')
    adjective3 = input('Enter an adjective: ')
    noun5 = input('Enter a noun: ')
    verb3 = input('Enter a verb (past tense): ')
    feeling = input('Enter a feeling: ')
    noun6 = input('Enter a noun: ')
    verb4 = input('Enter a verb: ') 
    noun7 = input('Enter a noun: ')
    verb5 = input('Enter a verb: ') 
    verb6 = input('Enter a verb: ')
    verb7 = input('Enter a verb: ')
    landmark = input('Enter a landmark: ')
    verb8 = input('Enter a verb: ')
    yourName = input('Enter your name: ')
    print('Dearest ' + partnerName2 + ', I am writing to you to ' + verb1 + 'my absolute ' + noun1 + ' and admiration of you. Your are the ' + noun2 + ' of my life and the ' + noun3 + ' of my eye. I wish to ' + verb2 + ' with you more than anything in the ' + noun4 + '. You are ' + adjective1 + ', ' + adjective2 + ', and' + adjective3 + '. From the ' + noun5 + ' we first ' + verb3 + ', I knew I was in ' + feeling + ' with you. Our ' + noun6 + ' has meant so much to me thus far, but I want to ' + verb4 + ' things to the next ' + noun7 + '. How do you ' + verb5 + '? Do you ' + verb6 + ' me too?' + ' I will be ' + verb7 + ' for you at the top of ' + landmark + ' at 8pm tomorrow. Hope to ' + verb8 + ' you soon. With Love,' + yourName)


Button(root, text='Wedding Vow', font='arial 15', command= madlib1, bg='ghost white').place(x=60, y=120)
Button(root, text='Love Letter', font='arial 15', command= madlib2, bg='ghost white').place(x=80, y=240)

root.mainloop()
